"""upgrade database

Revision ID: 27fe109e0120
Revises: 00000000
Create Date: 2019-04-03 13:33:22.339332

"""

# revision identifiers, used by Alembic.
revision = '27fe109e0120'
down_revision = '00000000'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('user')
    # op.drop_table('rel_user')
    # op.drop_table('rel_user_text')
    # op.drop_table('rel_user_multi')
    ### end Alembic commands ###

    op.execute('''UPDATE user SET point_balance=5000 WHERE user_id=1
    ''')
    op.execute('''ALTER TABLE user ADD location VARCHAR(50)
    ''')
    op.execute('''UPDATE user SET location="USQ" WHERE user_id=2
    ''')
    op.execute('''UPDATE user SET tier="Silver" WHERE user_id=3
    ''')
    


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('rel_user')
    op.drop_table('rel_user_text')
    op.drop_table('rel_user_multi')
    ### end Alembic commands ###
    
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rel_user_multi',
    sa.Column('rum_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('rel_lookup', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('attribute', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('create_transaction_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('rum_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('rel_user_text',
    sa.Column('rut_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('rel_lookup', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('attribute', mysql.TEXT(), nullable=True),
    sa.Column('create_transaction_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('rut_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('rel_user',
    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text(u"'0'"), autoincrement=False, nullable=False),
    sa.Column('rel_lookup', mysql.VARCHAR(length=128), server_default=sa.text(u"''"), nullable=False),
    sa.Column('attribute', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('create_transaction_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'rel_lookup'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('user',
    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('email_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('display_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('signup_date', sa.DATE(), nullable=True),
    sa.Column('enroll_status', mysql.VARCHAR(length=50), server_default=sa.text(u"'PreValid'"), nullable=False),
    sa.Column('enroll_complete', mysql.TINYINT(display_width=1), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    sa.Column('tier', mysql.VARCHAR(length=50), server_default=sa.text(u"'Carbon'"), nullable=False),
    sa.Column('last_interaction_dttm', mysql.TIMESTAMP(), nullable=True),
    sa.Column('group_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('current_ohm_service_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('point_balance', mysql.DOUBLE(asdecimal=True), server_default=sa.text(u"'0'"), nullable=False),
    sa.Column('credit_balance', mysql.DOUBLE(asdecimal=True), server_default=sa.text(u"'0'"), nullable=False),
    sa.Column('donated_points', mysql.DOUBLE(asdecimal=True), server_default=sa.text(u"'0'"), nullable=False),
    sa.Column('lifetime_points', mysql.DOUBLE(asdecimal=True), server_default=sa.text(u"'0'"), nullable=False),
    sa.Column('create_transaction_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
